# Generated by Django 6.0.2 on 2026-02-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattempt',
            name='correct_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
