# Generated by Django 6.0.2 on 2026-02-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillmap', '0002_assessmentattempt_correct_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattempt',
            name='wrong_answers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
