# Generated by Django 6.0.2 on 2026-02-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillmap', '0003_assessmentattempt_wrong_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattempt',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
    ]
